name: Run MyCommunity Scraper

on:
  schedule:
    - cron: '42 9 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4 gspread oauth2client

      - name: Run Scraper
        env:
          GOOGLE_SHEET_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_CREDENTIALS }}
        run: |
          echo "$GOOGLE_SHEET_CREDENTIALS" > mycommunitydirectorycredential.json
          python mycommunitydirectory.py
