name: Run mycommunitydirectory.py

on:
  schedule:
    - cron: '0 0 * * *'  # Adjust the cron schedule as needed
  workflow_dispatch:      # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository content

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 gspread oauth2client  # Install required packages
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute script
        run: python mycommunitydirectory.py

