name: Run Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Use a compatible Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 undetected-chromedriver

      - name: Install Chrome and ChromeDriver
        run: |
          choco install googlechrome --no-progress --yes
          choco install chromedriver --no-progress --yes
          setx PATH "%PATH%;C:\ProgramData\chocolatey\bin"

      - name: Verify Chrome and ChromeDriver Installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run Scraper
        env:
          CHROME_DRIVER_PATH: "C:\ProgramData\chocolatey\bin\chromedriver.exe"
        run: |
          python script.py

      - name: Upload Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: scraped-results
          path: categories_and_subcategories_results.csv
